name: deployment
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Build Code
        run: npm ci
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Build Code
        run: npm ci
      - name: Test Code
 #       run: npm run test
        run: echo "Testing...."
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Build Code
        run: npm ci
      - name: Test Code
        run: npm run test
      - name: Deploy Code
        run: echo "Deploying..."